---
nvidia_gpu_operator:
  gpu_namespace: "nvidia-gpu-operator"
  gpu_channel: "v24.3"
  nfd_namespace: "openshift-nfd"
  nfd_channel: "stable"
  gpu_driver_version: 550.90.07
  gpu_driver_repository_path: "nvcr.io/nvidia"
