---
instance_id: xxx

maf:
  enabled: true         # <â€” single source of truth for ON/OFF

resources:
  limits:
    cpu: "5"            # requirement from sizing (orderable)
    memory: 8Gi
  requests:
    cpu: 10m
    memory: 256Mi

persistentVolume:
  name: app-config
  size: 2Gi
  storageClassName: nfs-client

serviceAccount: ibm-mas-config-reader