---
instance_id: xxx

maf:
  enabled: true         # <â€” single source of truth for ON/OFF

image:
  repository: docker-na-proxy-rtp.artifactory.swg-devops.com/wiotp-docker-local/mas/graphite-configuration
  tag: 1.7.35-pre.maxuif-3049-amd64
  pullPolicy: Always

resources:
  limits:
    cpu: "5"            # requirement from sizing (orderable)
    memory: 8Gi
  requests:
    cpu: 10m
    memory: 256Mi

pvc:
  name: app-config
  size: 2Gi
  storageClassName: nfs-client

serviceAccount: ibm-mas-config-reader