ibm_aiservice_tenant:
  # aiservice
  tenant_id: "aiservice-t01"
  aiservice_namespace: "aiservice-inst-1-aiservice"
  aiservice_instance_id: "aiservice-inst-1"
  tenantNamespace: "aiservice-usr1"

  mas_icr_cp: "cp.icr.io/cp"
  mas_icr_cpopen: "icr.io/cpopen"

  # dro
  drocfg_url: "drocfg_url"
  drocfg_ca: "drocfg_ca"
  drocfg_registration_key: "drocfg_registration_key"

  # sls
  slscfg_ca_tenant: "slscfg_ca_tenant"
  slscfg_url: "slscfg_url"
  slscfg_registration_key: "slscfg_registration_key"
  aiservice_sls_subscription_id: "001"
  
  rsl_url: "rsl_url"
  rsl_org_id: "rsl_org_id"
  rsl_token: "rsl_token"
  rsl_ca_crt: "rsl_ca_crt"

  
  # watsonx
  aiservice_watsonxai_url: "aiservice_watsonxai_url"
  aiservice_watsonxai_project_id: "aiservice_watsonxai_project_id"
  aiservice_watsonxai_apikey: "aiservice_watsonxai_apikey"
  aiservice_watsonxai_on_prem: "false"
  aiservice_watsonxai_instance_id: ""
  aiservice_watsonxai_version: ""
  aiservice_watsonxai_username: ""

  tenant_entitlement_type: "standard"
  tenant_entitlement_start_date: "2025-06-11"
  tenant_entitlement_end_date: "2049-11-11"
  
  aiservice_operator_log_level: "2"