
---
apiVersion: addons.mas.ibm.com/v1
kind: GenericAddon
metadata:
  name: "{{ .Values.instance_id }}-addons-application-configuration"
  namespace: mas-{{ .Values.instance_id }}-core
  annotations:
    argocd.argoproj.io/sync-wave: "552"
  labels:
    mas.ibm.com/configScope: system
    mas.ibm.com/instanceId: {{ .Values.instance_id }}
{{- if .Values.custom_labels }}
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
spec:
  displayName: "{{ .Values.instance_id }}-application-configuration"
  addonType: application-configuration
  config:
    addonIdentifier: {{ .Values.instance_id }}
    instances:
      - name: "{{ .Values.instance_id }}-application-configuration"

