---
efs_csi_namespace: "openshift-cluster-csi-drivers"
efs_install_plan: Automatic
efs_subscription_source: redhat-operators
efs_subscription_sourceNamespace: openshift-marketplace

run_sync_hooks: true