---
efs_csi_driver:
  catalog_source: redhat-operators
  catalog_source_namespace: openshift-marketplace
  channel: stable
  role_arn: "arn:aws:iam::435377327995:role/MCSP_MAS_EFS_CSI_Policy_Role_mas-cluster-4"
merge-key: "aws-dev/mas-cluster-4"
