---
# This to prevent AVP from complaining about there being no manifests
# if none of the other resources in this chart end up being rendered
apiVersion: v1
kind: ConfigMap
metadata:
  name: reporter-placeholder
  namespace: "{{ .Values.reporter_namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "00"
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
data:
  nodata: ""