---
cpd_operators_namespace: "ibm-cpd-operators"
cpd_instance_namespace: "ibm-cpd"
ibm_entitlement_key: ""
cpd_admin_login_sa: "mas-cpd-cluster-admin-sa"
cpfs_channel: ""
cpfs_size: "small"
cpd_platform_cr_name: "ibmcpd-cr"
cpd_iam_integration: false
cpd_primary_storage_class: ""
cpd_metadata_storage_class: ""
