rds_admin_db_name: "rdsadmin"
host: "xyz.db"
port: 50000
dbname: "rds1"
user: "dummy"
password: "dummy"

db2_rds_instance_name: dbs-rds-inst1-manage
scriptConfigMapName: dbs-rds-init-script
mas_application_id:
