# Basic connection configuration
rds_admin_db_name: "rdsadmin"
host: "xyz.db"
port: 50000
dbname: "rds1"
user: "dummy"
password: "dummy"

# Additional basic values
db2_namespace: ""
mas_application_id: ""  # manage, facilities, or iot
jdbc_connection_url: ""
replica_db: false

# DB2 Instance Registry Configuration
db2_instance_registry: {}

# DB2 Database Configuration
db2_database_db_config: {}

# DB2 Audit Configuration
db2_addons_audit_config:
  enableAudit: false
  applyDefaultPolicy: false

# DB2 Instance DBM Configuration
db2_instance_dbm_config: {}

# Script and application configuration
db2_rds_instance_name: dbs-rds-inst1-manage
scriptConfigMapName: dbs-rds-init-script
mas_application_id: ""