---
run_sync_hooks: true
mas_manual_cert_mgmt: "False"
gpu_request_quota: "2"

# ####################################################
# # Required values. No defaults provided.
# # Values shown here are for illustration purposes only
# ####################################################

# instance_id: "instance1"
# mas_app_id: "manage"
# mas_app_namespace: "mas-instance1-manage"
# mas_app_api_version: "apps.mas.ibm.com/v1"
# mas_app_kind: "ManageApp"
# argo_namespace: "openshift-gitops"
# ibm_entitlement_key: "<base64-encoded JSON>"
# mas_app_catalog_source: "ibm-operator-catalog"
# mas_edition "essentials-inspection"
# mas_app_spec:
#   settings:
#   ...


# ####################################################
# # Required iff mas_manual_cert_mgmt is "True"
# ####################################################
# public_tls_secret_name: "public-tls-cert"
# ca_cert: "<base64-encoded PEM>"
# tls_cert: "<base64-encoded PEM>"
# tls_key: "<base64-encoded PEM>"